name: Build Buf
description: A GitHub action that provides buildbuf/buf

inputs:
  bufVersion:
    description: The version of buf to use (as in their GitHub releases)
    default: v0.31.1
    required: false
  bufArgs:
    description: The arguments to pass to buf
    default: check lint
    required: false
  protocPlugins:
    description: The protoc language plugins to install, space separated. See README for supported plugins.
    default: "none"
    required: false

runs:
  using: composite
  steps:
    #    requires actions within actions as tracked in https://github.com/actions/runner/issues/646
    #    - uses: actions/cache@v2
    - name: Maybe install and definitely invoke buf
      shell: bash
      run: |
        REPO_DIR="$(pwd)"
        cd ${{ github.action_path }}
        source scripts/install-buf.sh ${{ inputs.bufVersion }} "${{ inputs.protocPlugins }}"
        cd $REPO_DIR
        buf ${{ inputs.bufArgs }}

branding:
  color: blue
  icon: box
