name: Format

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make format
      - name: Indicate formatting issues
        run: git diff HEAD --exit-code --color
